server:
  port: 9528
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
spring:
  profiles:
    active: mysql
  datasource:
    druid:
      # 配置测试查询语句
      validation-query: SELECT 1
      filters: stat,slf4j
#      filter:
#        wall:
#          config:
#            variantCheck: false
#            noneBaseStatementAllow: true
#            commentAllow: true
#            multiStatementAllow: true
