spring:
  datasource:
    url: jdbc:mysql://localhost/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zero
zero:
  ac-table:
    entity-package: io.gitee.zerowsh.actable.demo.entity.mysql
    model: ADD_OR_UPDATE_OR_DEL
    script: db/mysql.sql
