spring:
  datasource:
    url: jdbc:mysql://localhost/dynamic_table?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zero
zero:
  mybatis:
    ac-table:
      database-type: mysql
