spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=dynamic_table
    username: sa
    password: zero
zero:
  ac-table:
    entity-package: io.gitee.zerowsh.actable.demo.entity.sqlserver
    model: ADD_OR_UPDATE_OR_DEL
    script: db/sql_server.sql
    database-type: sql_server