spring:
  datasource:
    url: jdbc:dm://localhost:5236/TEST
    username: SYSDBA
    password: SYSDBA001
#    url: jdbc:dm://192.168.0.222:15236/BASE
#    username: BASE
#    password: 2024qwe,.
zero:
  ac-table:
    entity-package: io.gitee.zerowsh.*.demo.entity
    model: ADD_OR_UPDATE_OR_DEL
#    after-script: db/mysql.sql
    history: NONE
    print: true
