spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=dynamic_table
    username: sa
    password: zero
zero:
  ac-table:
    entity-package: io.gitee.zerowsh.actable.demo.entity
    model: ADD_OR_UPDATE_OR_DEL
    after-script: db/sql_server.sql
